apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-app-deployment
  labels:
    app: quotes-app
spec:
  replicas: 4
  template:
    metadata:
      name: quotes-app-pod
      labels:
        app: quotes-app
    spec:
      containers:
        - name: quotes-app-container
          image: gogulasudheer/i-sudheergogula
          envFrom:
            - configMapRef:
                name: quotes-config
            - secretRef:
                name: quotes-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3
  selector:
    matchLabels:
      app: quotes-app
